AWSTemplateFormatVersion: '2010-09-09'

Description: Template to create Quest task definition and deploy the service with a DNS record

Resources:

  QuestAppTaskDef:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: "Quest"
      RequiresCompatibilities:
        - EC2
      NetworkMode: bridge
      ExecutionRoleArn: !ImportValue "quest:AppTaskRole"
      Cpu: "512"
      Memory: "512"
      ContainerDefinitions:
        - Name: "Quest"
          PortMappings:
            - ContainerPort: 3000
              HostPort: 0
          Environment:
            - Name: SECRET_WORD
              Value: "TwelveFactor"
          Essential: true
          Image: 981354137213.dkr.ecr.us-east-1.amazonaws.com/quest:latest

  QuestAppService:
    DependsOn: QuestListenerRuleHTTP
    Type: AWS::ECS::Service
    Properties:
      Cluster: !ImportValue "quest:ClusterArn"
      LaunchType: EC2
      LoadBalancers:
        - ContainerName: "Quest"
          ContainerPort: 3000
          TargetGroupArn: !ImportValue "quest:QuestTG"
      DeploymentConfiguration:
        MaximumPercent: 200
        MinimumHealthyPercent: 100
      DesiredCount: 1
      TaskDefinition: !Ref "QuestAppTaskDef"
      PlacementStrategies:
        - Type: spread
          Field: attribute:ecs.availability-zone

  QuestListenerRuleHTTP:
    Type: AWS::ElasticLoadBalancingV2::ListenerRule
    Properties:
      Actions:
        - TargetGroupArn: !ImportValue "quest:QuestTG"
          Type: forward
      Conditions:
        - Field: path-pattern
          Values: 
            - "/*"
      ListenerArn: !ImportValue "quest:HTTPListener"
      Priority: 1

  QuestListenerRuleHTTPS:
    Type: AWS::ElasticLoadBalancingV2::ListenerRule
    Properties:
      Actions:
        - TargetGroupArn: !ImportValue "quest:QuestTG"
          Type: forward
      Conditions:
        - Field: path-pattern
          Values:
            - "/*"
      ListenerArn: !ImportValue "quest:HTTPSListener"
      Priority: 1

#  QuestRecord:
#    Type: AWS::Route53::RecordSet
#    Properties:
#      ResourceRecords:
#        - "alb.quest.net."
#      HostedZoneId: !ImportValue "quest:HostedZone"
#      Name: "endpoint.quest.net"
#      Type: CNAME
#      TTL: '300'