AWSTemplateFormatVersion: '2010-09-09'

Description: Repository for Quest image

Parameters:
  
  IAMARN:
    Description: ARN to give access to the ECR
    Type: String

Resources:

  QuestECR:
    Type: AWS::ECR::Repository
    Properties: 
      RepositoryName: "quest"
      RepositoryPolicyText: 
        Version: "2012-10-17"
        Statement: 
          - 
            Sid: AllowPushPull
            Effect: Allow
            Principal: 
              AWS: 
                - !Ref IAMARN
            Action: 
              - "ecr:GetDownloadUrlForLayer"
              - "ecr:BatchGetImage"
              - "ecr:BatchCheckLayerAvailability"
              - "ecr:PutImage"
              - "ecr:InitiateLayerUpload"
              - "ecr:UploadLayerPart"
              - "ecr:CompleteLayerUpload"
