AWSTemplateFormatVersion: '2010-09-09'

Description: Hosted zone for quest

Parameters:

  VPCID:
    Description: AWS VPC to deploy ALB into
    Type: String

Resources:

  QuestRoute53HostedZone:
    Type: AWS::Route53::HostedZone
    Properties:
      Name: "quest.net"
      HostedZoneConfig:
        Comment: "Hosted zone for Quest"
      VPCs:
        - VPCId: !Ref VPCID
          VPCRegion: !Ref AWS::Region

Outputs:

  QuestRoute53ZoneId:
    Value: !Ref QuestRoute53HostedZone
    Export:
      Name: "quest:HostedZone"